### ISSUE TITLE
VSCode does not recognize "phpclassgen.vendor" setting

### ISSUE THREAD

**Issue by devaneando** [damianbal/vs-phpclassgen#2]
I can see i the plugin the documentation page that it has a setting:

> phpclassgen.vendor: set it to your name, or leave it blank if you do not want any prefix in namespaces.

But that option is not displayed in the settings editor.

If I edit the `settings.json` file directly and add the `"phpclassgen.vendor": "App"`, the prefix will be appended correctly to the namespace, but VSCode will give me a **Unknow configuration setting** warning. 

I'm using `VSCode 1.32.1` and `PHP Class Generator 0.0.24`

**Comment by damianbal** [comment]
I will look into that, thanks for reporting.

**Comment by damianbal** [comment]
This problem is now resolved with 0.1.0 version, and this setting can be set using new settings editor as well.
