### ISSUE TITLE
Namespaces are not parsed from (Windows?) path

### ISSUE THREAD

**Issue by manierim** [damianbal/vs-phpclassgen#3]
Running VSV 1.33.1 on Windows 10
Lumen app

I always got empty namespaces with any command for code in 'app' directory.
Looking to the source code I guess the problem might be in utils.js line 26:

    let pathElements = filePath.split("/");

Windows paths use backslashes \...

**Comment by damianbal** [comment]
Thanks for reporting that, I developed it on mac so this is why it is like that. When I will have a spare time I will rewrite that extension with added settings for new settings editor and I will make sure it works on windows as well.

**Comment by damianbal** [comment]
This problem should be resolved now as of 0.1.0 version.
