### ISSUE TITLE
Running the contributed command: 'phpclassgen.generate_class' failed.

### ISSUE THREAD

**Issue by kapersoft** [damianbal/vs-phpclassgen#7]
When I run a command I get an error message: `Running the contributed command: 'phpclassgen.generate_class' failed.`.

This problem is fixed when the `phpclassgen.vendor`-setting is set to a non-null value (e.g. `"phpclassgen.vendor": ""`).

Can you fix this? Or should I sent in a PR?

**Comment by damianbal** [comment]
Should be fixed by now, hopefully 👍
